CFLAGS=-O2 -g

all:
	g++ $(CFLAGS) naive.cpp -o naive.out
	g++ $(CFLAGS) recursive.cpp -o recursive.out
	g++ $(CFLAGS) leftright.cpp -o leftright.out
	g++ $(CFLAGS) leftright2.cpp -o leftright2.out

clean:
	rm -rf *.o *.out
